base:
  app_chain_type: fisco # application chain type
  store_path: .db # store path

# iservice config
iservice:
  chain_id: irita
  node_rpc_addr: http://127.0.0.1:26657
  node_grpc_addr: 127.0.0.1:9090
  key_path: .keys/iservice
  key_name: node0
  passphrase: 1234567890

# fisco config
fisco:
  connection_type: channel
  ca_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/ca.crt
  cert_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/sdk.crt
  key_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/sdk.key
  sm_crypto: true
  priv_key_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/key.pem

# mysql config
mysql:
  db_name: relayer
  db_user_name: root
  db_user_passphrase: 123456
  host: localhost
  port: 3306